# Generated by Django 4.0.5 on 2022-06-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_profile_profile_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='e_mail',
            field=models.EmailField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user_name',
            field=models.CharField(default=2, max_length=64),
            preserve_default=False,
        ),
    ]
