# Generated by Django 4.0.5 on 2022-06-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_e_mail_profile_firstname_profile_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='e_mail',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_name',
        ),
    ]
