# Generated by Django 4.0.5 on 2022-06-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_profile_e_mail_remove_profile_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatives',
            name='link',
            field=models.CharField(choices=[('son', 'Son'), ('daughter', 'Daughter'), ('brother', 'Brother'), ('sister', 'Sister'), ('mother', 'Mother'), ('father', 'Father')], max_length=32),
        ),
    ]
