# Generated by Django 4.0.5 on 2022-06-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_relatives_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatives',
            name='link',
            field=models.CharField(choices=[('Son', 'Son'), ('Daughter', 'Daughter'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Mother', 'Mother'), ('Father', 'Father')], max_length=32),
        ),
    ]
